name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Update CDN with minified version
        uses: datamonsters/replace-action@master
        with:
          files: "index.html"
          replacements: "dist/vue.js=dist/vue.min.js,vuetify.js=vuetify.min.js,vue-router.js=vue-router.min.js,vuex.js=vuex.min.js"

      - name: Update vite base path for GitHub Pages
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "base: ''"
          replace: "base: '/${{ github.event.repository.name }}/'"
          include: vite.config.js

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
